[versions]
paper = "1.20.4-R0.1-SNAPSHOT"
jspecify = "1.0.1"
errorprone = "2.50.0"
nullaway = "0.14.2"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.1.0" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.10.3" }
errorprone = { id = "net.ltgt.errorprone", version = "5.1.1" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.37.0" }
